### PR TITLE
Add: support for actuator

### PR DESCRIPTION
**Pull request by Timvdv**
Je kan nu een POST request doen naar: http://xxx/actuator/:device_token

met `{"actuator":"false"}` of `{"actuator":"true"}`

Deze value kun je ophalen met een GET op http://xxx/actuator/:device_token

### CODE REVIEW

**Comment by ianwensink** [comment]
@Timvdv nice. Enig idee waarom de tests falen? Als je lokaal `yarn test` doen, wat is dan de log?

**Comment by Timvdv** [comment]
@ianwensink ```
yarn lint v0.27.5
$ eslint src

/Users/Tim/Projects/iot-open-server/src/index.js
   7:3  warning  Unexpected console statement  no-console
  11:3  warning  Unexpected console statement  no-console
  16:3  warning  Unexpected console statement  no-console

/Users/Tim/Projects/iot-open-server/src/middleware/admin.js
  14:44  warning  Unexpected dangling '_' in '_id'  no-underscore-dangle
  44:3   warning  Unexpected console statement      no-console
  46:11  warning  Unexpected dangling '_' in '_id'  no-underscore-dangle
  58:3   warning  Unexpected console statement      no-console
  62:11  warning  Unexpected dangling '_' in '_id'  no-underscore-dangle
  73:31  warning  Unexpected dangling '_' in '_id'  no-underscore-dangle

/Users/Tim/Projects/iot-open-server/src/middleware/api.js
  12:5   warning  Assignment to property of function parameter 'device'    no-param-reassign
  14:17  warning  Unexpected dangling '_' in '_id'                         no-underscore-dangle
  22:9   warning  Assignment to property of function parameter 'dataType'  no-param-reassign
  23:9   warning  Assignment to property of function parameter 'dataType'  no-param-reassign
  27:12  warning  Assignment to property of function parameter 'device'    no-param-reassign
  28:12  warning  Assignment to property of function parameter 'device'    no-param-reassign
  29:12  warning  Unexpected dangling '_' in '__v'                         no-underscore-dangle
  29:12  warning  Assignment to property of function parameter 'device'    no-param-reassign
  30:12  warning  Assignment to property of function parameter 'device'    no-param-reassign

/Users/Tim/Projects/iot-open-server/src/templates/form.js
  7:51  warning  Unexpected dangling '_' in '_id'  no-underscore-dangle

✖ 19 problems (0 errors, 19 warnings)

Done in 2.62s.
```

**Comment by ianwensink** [comment]
@Timvdv dat is `yarn lint`, ik wil graag `yarn test` ;-) Linting gaat gewoon goed namelijk

**Comment by Timvdv** [comment]
@ianwensink yarn test werkt helemaal niet

```
yarn test v0.27.5
$ nyc tape tests/unit/*.js | tap-nyc
    ----------|----------|----------|----------|----------|----------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
    ----------|----------|----------|----------|----------|----------------|
    All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
    ----------|----------|----------|----------|----------|----------------|

error Command failed with exit code 1.
```

**Comment by ianwensink** [comment]
Oh dan @bartlangelaan

**Comment by Timvdv** [comment]
Kunnen we die CI er niet gewoon uitslopen?

**Comment by ianwensink** [comment]
Tuurlijk kan dat, maar willen we dat...

**Pull request merged**
